services:
  quotation-service:
    image: mostela/desafiocotacoes
    container_name: quotation_service
    ports:
      - "3000:3000"
    networks:
      - quotation-network

  web:
    build: .
    container_name: quotation_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - quotation-service
    networks:
      - quotation-network

networks:
  quotation-network:
    driver: bridge
